---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    output_log: true
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian10}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        wkhtmltopdf_version: "0.12.5"
verifier:
  name: ansible
